## TaskGroup
```swift
이제는 많은것들을 배운후라 async let 바인딩을 통한 작업 병렬 실행에 익숙할것이다.
async let 바인딩은 특히 일부 작업을 병렬로 실행해야 하고 다른 작업은 서로 의존하며 순차적으로 실행해야하는경우
비동기 흐름을 설계하는데 도움이되는 강력한 메커니즘이다.

async let을 사용하여 실행할 작업 수와 어떤 작업을 실행할지 결정하는 유연성이 있지만 
해당 구문은 실제로 동시성을 제공하지는 않는다.
만약 수천개의 작업을 병렬로 실행해야 한다고 가정해보자. async let을 천번 작성하는것은 불가능하다.
또는 미리 얼마나 많은 수의 병렬 작업을 해야할지 모르는경우 ex) 서버에서 내려주는 리스트?
이런경우 실행시점에서 이러한 처리를 결정해야한다.

TaskGroup은 코드에서 동적 동시성을 생성할 수 있게 해주는 현대적인 API 이다.
TaskGroup은 코드 내에서 동시성을 신속하게 생성할 수 있도록 해주며 데이터 경쟁의 가능성을 줄이고 결과를 안전하게 처리할 수 있게 해준다.

TaskGroup을 구성하는데 사용되는 두가지 변형이 있다.
TaskGroup과 ThrowingTaskGroup
다른것들과 마찬가지로 두 변형은 거의 동일하다.
차이점은 예외를 던질수 있냐 없냐의 차이다.

TaskGroup을 직접 초기화 하지 않는다. 왜냐하면 두 API 모두 이니셜라이저를 제공하지 않는다. 
대신 다음과 같은 유용한 제네릭 함수중 하나를 사용하여 그룹을 생성하고 코드를 올바르게 타입체크하는데 컴파일러를 제공한다.
withTaskGroup(of:returning:body:):
주어진 작업 반환 유형, 그룹 내 작업에서 생성할 최종 결과에 대한 주어진 반환 유형 및 본문 클로저를 사용하여 그룹을 생성한다.
withThrowingTaskGroup(of:returning:body:): 
유사한 매개변수를 사용하지만, 각 작업뿐만 아니라 그룹 전체가 오류를 던질 수 있다.

이러한 함수에 대한 중요한점은 그룹이 모든 작업을 실행한 후에만 반환된다는 것이다.
한번 사용해보자.

일단 기존에 사용하던 이미지를 가져오는 함수를 쓸것이다.
    private func fetchImage() async throws -> UIImage? {
        guard let url = URL(string: "https://source.unsplash.com/random") else {
            throw CustomError.urlError
        }
        let (data, response) = try await URLSession.shared.data(from: url)
        guard let httpResponse = response as? HTTPURLResponse, httpResponse.statusCode == 200 else {
            throw CustomError.responseError
        }

        let image = UIImage(data: data)
        return image
    }
    
    그리고 View를 만들자
    
struct ContentView: View {

    @State var images: [UIImage?] = []

    var body: some View {
        ScrollView {
            ForEach(images, id: \.self) {
                if let image = $0 {
                    Image(uiImage: image)
                }
            }
        }
    }
}

그리고 이제 TaskGroup을 이용해서 여러개의 이미지를 병렬적으로 가져오는 함수를 만들자.

   private func setTask() async throws -> [UIImage?] {
        let images = try await withThrowingTaskGroup(of: UIImage?.self, returning: [UIImage?].self) { group in
            for _ in 0...10 {
                group.addTask {
                    return try await fetchImage()
                }
            }
            return try await group.reduce(into: []) { partialResult, image in
                partialResult.append(image)
            }
        }
        return images
    }
    
일잔 withThrowingTaskGroup 함수에 of 파라미터에는 각각의 작업이 반환하는 타입을 쓰고
          of: UIImage?.self

returning에는 최종적으로 반환할 타입을 쓴다.
           returning: [UIImage?].self
    
그리고 클로져 안에 반복되는 작업을 수행하면 된다. 여기선 for 문을 이용해 fetchImage 함수를 여러번 작동시킨다.
            for _ in 0...10 {
                group.addTask {
                    return try await fetchImage()
                }
            }

모든 작업들이 완료되면 해당 그룹에 모인 각각의 작업들의 아이템을 어떻게 할지 처리한다.

            return try await group.reduce(into: []) { partialResult, image in
                partialResult.append(image)
            }


그리고는 사용할 곳에서 
        .task {
            do {
                let images = try await setTask()
                self.images = images
            } catch let error {
                print("debug \(error)")
            }
        }
        
이렇게 사용하면 된다.

TaskGrop의 경우 다음과 같은 메서드가 있다.

• addTask(priority:operation:): 주어진 (선택적) 우선 순위로 그룹에 작업을 추가하여 동시 실행한다.
• addTaskUnlessCancelled(priority:operation:): addTask(...)와 동일하지만, 그룹이 이미 취소된 경우 아무 작업도 수행하지 않는다.
• cancelAll(): 현재 실행 중인 모든 작업과 미래에 추가될 모든 작업을 모두 취소한다.
• isCancelled: 그룹이 취소되었으면 true를 반환한다.
• isEmpty: 그룹이 모든 작업을 완료했거나 아무 작업도 없으면 true를 반환한다.
• waitForAll(): 모든 작업이 완료될 때까지 기다린다. 그룹의 작업을 완료한 후에 코드를 실행해야 할 때 사용한다.

TaskGroup이 AsyncSequence를 준수하기 때문에 일반적인 Swift Sequnece 처럼 그룹을 비동기적으로 반복할수 있다.

```

## 공유 상태 변경
```swift
TaskGroup을 사용할때 중요한점은 실제로 코드의 어느 부분이 병렬로 실행되는지 이해 하는것이다.

설계상으로는 작업에서 별령 실행의 모든 결과를 반환하고 그결과를 그룹을 통해 안전하게 수집할수 있다.
그러나 때로는 작업 그룹 내부에서어떤 종류의 공유 상태를 직접 업데이트해야할때가 있다.

예를들어서
서버에서 파일을 다운로드하는 병렬 작업은 공유 앱 로거 객체를 통해서 즉시 결과를 로깅할수 있다.
이렇게하면 파일중 하나의 다운로드가 실패하고 요청이 오류를 throw 하는 경우에도 다른 요청은 파일을 받으면 성공적으로 로깅한다.

공유 상태를 변경하는경우 경쟁상태가 발생할수 있다. 경쟁상태는 메모리에서 동일한 데이터에 여러 스레드가 엑세스하고 그중 적어도 하나가 데이터를 변경하거나 수정하려고 할때 발생한다.
경쟁상태의 까다로운 부분은 xcode의 디버그 모드에서 앱을 실행할때 거의 충돌을 경험하지 않는다는것이다.
경쟁상태는 주로 앱을 릴리즈후에 사용자의 디바이스에서 실행할때 충돌을 유발한다. 
요약 하자면 작업 그룹 코드의 어느 부분이 동시에 실행되는지 주의해야한다.

이에 대한 해결방법은 MainActor 파트에서 배울것이다.
```

## TaskGroup 에러 핸들링
```swift
지금까지 TaskGroup을 실행하는것은 정말 쉬웠다.
하지만 떄때로 ScanTask.run()은 실패할 것이고, 그 결과를 다뤄야 할것이다.

fetchImage 함수에 파라미터를 추가하자

    private func fetchImage(index: Int) async throws -> (UIImage?) {


그리고 TaskGrop 생성 For문에서 index를 넣어주자

            for index in 0...10 {
                group.addTask {
                    return try await fetchImage(index: index)
                }
            }
            
그 뒤에 fetchImage 함수에 다시 코드를 추가하자
        if index == 5 {
            throw CustomError.defaultError
        }

그러고 실행을 해보자.
이 동작의 결과로 작업 중 하나가 에러를 던지면 전체 그룹이 중단되는것을 볼수 있다.
더 이상 작업이 실행 되지 않을뿐더러 이미 실행된 작업의 결과 또한 받을수 없다.

이 코드를 한번 실패한 작업 무시하고 성공적으로 반환된 모든 작업의 결과를 수집하도록 바꿔보자.

오류를 안전하게 처리하기위해 오류를 던지지않고 Result 타입을 사용할것이다.

fetchImage 함수 먼저 수정하자
    private func fetchImage(index: Int) async -> Result<UIImage?, Error> {
        if index == 5 {
            return .failure(CustomError.defaultError)
        }
        guard let url = URL(string: "https://source.unsplash.com/random") else {
            return .failure(CustomError.urlError)
        }
        do {
            let (data, response) = try await URLSession.shared.data(from: url)
            guard let httpResponse = response as? HTTPURLResponse, httpResponse.statusCode == 200 else {
                return .failure(CustomError.failedResponse)
            }

            let image = UIImage(data: data)
            return .success(image)
        } catch let error {
            return .failure(error)
        }
    }
    
error를 throw 하는것이아니라 .failure로 반환 하는것이다..

그리고 taskGroup을 만드는 함수 역시 수정하자.

    private func setTask() async -> [UIImage?] {
        let images = await withTaskGroup(of: Result<UIImage?, Error>.self) { group -> [UIImage?] in
            for index in 0...10 {
                group.addTask {
                    return await fetchImage(index: index)
                }
            }

            return await group.reduce(into: []) { partialResult, image in
                switch image {
                case .success(let image):
                    partialResult.append(image)
                case .failure(let error):
                    print("debug \(error)")
                }
            }
        }
        return images
    }
    
에러를 던질수 있는 그룹을 굳이 사용할 필요가 없다.
이렇게히면 이제 실패한 작업을 건너뛰고 9개의 사진만 로드하는것을 확인할수 있다.

```

## 키포인트
- 임의의 개수의 동시작업을 실행하려면 TaskGroup을 이용하자.   
이를 위해서 withTaskGroup 함수를 사용하자 에러를 던지는경에는 withThrowingTaskGroup를 사용하자.   
- addTask 또는 addTaskUnlessCancelled를 호출해 그룹에 작업을 추가할 수 있다.    
- 에러를 반환하는 대신 Result 타입을 사용해서 모든 작업이 중지되는것을 방지할수있다.     
